services:
  - type: web
    name: save-me-bot
    env: docker
    plan: free
    dockerCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://save-me-bot.onrender.com
      - key: PORT
        value: 8443
      - key: DATABASE_PATH
        value: /app/data/save_me_bot.db
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_REMINDER_HOURS
        value: 168
      - key: MIN_REMINDER_HOURS
        value: 1
    buildFilter:
      paths:
        - "**"
      ignoredPaths:
        - "*.md"
        - "*.txt"
        - ".git/**"
        - "**/__pycache__/**"
        - "*.db"
        - "*.sqlite"
