services:
  - type: web
    name: save-me-bot
    env: docker
    plan: free
    
    # CRITICAL: Tells Render where to find the Dockerfile
    dockerfilePath: ./Dockerfile
    
    healthCheck:
      # CRITICAL: Keeps your free service alive
      path: /

    # Your environment variables. Render will handle the PORT automatically.
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://save-me-bot.onrender.com
      - key: DATABASE_PATH
        value: /app/data/save_me_bot.db
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_REMINDER_HOURS
        value: 168
      - key: MIN_REMINDER_HOURS
        value: 1
